

import { useEffect } from "react"
import { useForm } from "react-hook-form"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Loader2 } from "lucide-react"
import { toast } from "sonner"
import type { AxiosError } from "axios"

import { Button } from "@/components/ui/button"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog"
import {
    Form,
    FormControl,
    FormDescription,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form"
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import { updateOrganisation, getBranches } from "@/services/settingsService"

interface MetaAccountConfigDialogProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    account: any // The specific account object being configured
    integrations: any // Full integrations object to preserve other keys
}

export function MetaAccountConfigDialog({ open, onOpenChange, account, integrations }: MetaAccountConfigDialogProps) {
    const queryClient = useQueryClient()

    // Fetch branches
    const { data: branchesData } = useQuery({
        queryKey: ['branches'],
        queryFn: getBranches
    });
    const branches = branchesData?.branches || [];

    const form = useForm<{ branchId: string }>({
        defaultValues: {
            branchId: account?.branchId || "all_branches_placeholder"
        }
    })

    useEffect(() => {
        if (open && account) {
            form.reset({
                branchId: account.branchId || "all_branches_placeholder"
            })
        }
    }, [open, account, form])

    const mutation = useMutation({
        mutationFn: (data: { branchId: string }) => {
            const allAccounts = integrations.metaAccounts || [];

            // update the specific account in the array
            const updatedAccounts = allAccounts.map((acc: any) => {
                if (acc.adAccountId === account.adAccountId && acc.pageId === account.pageId) {
                    return { ...acc, branchId: data.branchId === "all_branches_placeholder" ? null : data.branchId }
                }
                return acc
            })

            // Construct full payload properly preserving other keys
            const updatedIntegrations = {
                ...integrations,
                metaAccounts: updatedAccounts
            };

            return updateOrganisation({ integrations: updatedIntegrations })
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["organisation"] })
            toast.success(`Branch settings saved for ${account.adAccountName || 'Account'}`)
            onOpenChange(false)
        },
        onError: (error: AxiosError<{ message: string }>) => {
            toast.error(error.response?.data?.message || "Failed to update settings")
        },
    })

    function onSubmit(values: { branchId: string }) {
        mutation.mutate(values)
    }

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Configure Meta Account</DialogTitle>
                    <DialogDescription>
                        Set the default branch for leads generated by <strong>{account?.adAccountName || account?.pageName || 'this account'}</strong>.
                    </DialogDescription>
                </DialogHeader>
                <Form {...form}>
                    <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                        <FormField
                            control={form.control}
                            name="branchId"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Target Branch</FormLabel>
                                    <Select
                                        onValueChange={field.onChange}
                                        defaultValue={field.value}
                                        value={field.value}
                                    >
                                        <FormControl>
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select a branch" />
                                            </SelectTrigger>
                                        </FormControl>
                                        <SelectContent>
                                            <SelectItem value="all_branches_placeholder">All Branches / Head Office</SelectItem>
                                            {branches.map((branch: any) => (
                                                <SelectItem key={branch.id} value={branch.id}>
                                                    {branch.name}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <FormDescription>
                                        Leads from this account will be assigned to this branch.
                                    </FormDescription>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <DialogFooter>
                            <Button type="submit" disabled={mutation.isPending}>
                                {mutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                Save Configuration
                            </Button>
                        </DialogFooter>
                    </form>
                </Form>
            </DialogContent>
        </Dialog>
    )
}
